name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Package
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git*'
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_utl: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: TrackStuff-wotlk.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
